name: 'Dependency-track-gh-action'
author: Neeraj Subramaniyan
description: 'Publishes BOMs to Dependency-Track and adds vulnerability info to PR comments'
inputs:
  serverhostname:
    description: 'Dependency-Track hostname'
    required: true
  port:
    description: 'Dependency-Track port'
    required: false
    default: 443
  apikey:
    description: 'Dependency-Track API key'
    required: true
  projectname:
    description: 'Project name in Dependency-Track'
    required: true
  projectversion:
    description: 'Project version in Dependency-Track'
    required: true
  autocreate:
    description: "Automatically create the project in Dependency-Track if it doesn't exist"
    default: 'false'
    required: false
  bomfilename:
    description: 'Path and filename of the BOM'
    default: 'bom.xml'
    required: false
runs:
  using: 'node12'
  main: 'index.js'